name: EnderSwap
main: com.github.dublekfx.EnderSwap.EnderSwap
version: 1.0
commands:
  enderswap:
    description: Toggle Player swapping on Enderpearl impact
    usage: /enderswap
    permission: enderswap.toggle
    permission-message: A voice whispers "You need enderswap.toggle"...
permissions:
  enderswap.toggle:
    description: Permits user to turn Enderswap on or off
    default: op